name: orbiview
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyqt=6.7
  - opencv=4.10
  - pyqtgraph
  - pyserial
  - numpy
  - ffmpeg
  - tesseract
  - mysql
  - openssl
  - pip
  - pip:
      - blinker==1.9.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - dash==3.2.0
      - flask==3.1.2
      - idna==3.10
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - narwhals==2.4.0
      - nest-asyncio==1.6.0
      - pandas==2.3.2
      - plotly==6.3.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - retrying==1.4.2
      - six==1.17.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - zipp==3.23.0
